/* SS_DEPARTMENTS Table */
DECLARE iCount NUMBER;
BEGIN
	SELECT COUNT(*) INTO iCount FROM user_tables WHERE table_name = 'SS_DEPARTMENTS';
	IF (iCount = 0) THEN
		EXECUTE IMMEDIATE 'CREATE TABLE SS_DEPARTMENTS (Department_Id NUMBER, Department_Name VARCHAR2(200 BYTE), Department_Code VARCHAR2(4 BYTE))';
		EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX SS_DEPARTMENTS_PK ON SS_DEPARTMENTS ("DEPARTMENT_ID")';
		EXECUTE IMMEDIATE 'ALTER TABLE SS_DEPARTMENTS ADD CONSTRAINT SS_DEPARTMENTS_PK PRIMARY KEY ("DEPARTMENT_ID")';
	END IF;
END;