/* SS_MAINT_STATUSES Table */
DECLARE iCount NUMBER;
BEGIN
	SELECT COUNT(*) INTO iCount FROM user_tables WHERE table_name = 'SS_MAINT_STATUSES';
	IF (iCount = 0) THEN
		EXECUTE IMMEDIATE 'CREATE TABLE SS_MAINT_STATUSES (Status_Id NUMBER, Maint_Status_Maintenance_Id NUMBER)';
		EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX SS_MAINT_STATUSE_SPK ON SS_MAINT_STATUSES ("STATUS_ID")';
		EXECUTE IMMEDIATE 'ALTER TABLE SS_MAINT_STATUSES ADD CONSTRAINT SS_MAINT_STATUSES_PK PRIMARY KEY ("STATUS_ID")';
	END IF;
END;