/* SS_ONLINE_STATUSES Table */
DECLARE iCount NUMBER;
BEGIN
	SELECT COUNT(*) INTO iCount FROM user_tables WHERE table_name = 'SS_ONLINE_STATUSES';
	IF (iCount = 0) THEN
		EXECUTE IMMEDIATE 'CREATE TABLE SS_ONLINE_STATUSES (Status_Id NUMBER, Online_Status_Online_Since DATE)';
		EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX SS_ONLINE_STATUSES_PK ON SS_ONLINE_STATUSES ("STATUS_ID")';
		EXECUTE IMMEDIATE 'ALTER TABLE SS_ONLINE_STATUSES ADD CONSTRAINT SS_ONLINE_STATUSES_PK PRIMARY KEY ("STATUS_ID")';
	END IF;
END;