/* SS_SERVICE_STATUSES Table */
DECLARE iCount NUMBER;
BEGIN
	SELECT COUNT(*) INTO iCount FROM user_tables WHERE table_name = 'SS_SERVICE_STATUSES';
	IF (iCount = 0) THEN
		EXECUTE IMMEDIATE 'CREATE TABLE SS_SERVICE_STATUSES (Service_Status_Status_Id NUMBER, Service_Status_Service_Id NUMBER)';
		EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX SS_SERVICE_STATUSES_PK ON SS_SERVICE_STATUSES ("SERVICE_STATUS_STATUS_ID", "SERVICE_STATUS_SERVICE_ID")';
		EXECUTE IMMEDIATE 'ALTER TABLE SS_SERVICE_STATUSES ADD CONSTRAINT SS_SERVICE_STATUSES_PK PRIMARY KEY ("SERVICE_STATUS_STATUS_ID", "SERVICE_STATUS_SERVICE_ID")';
	END IF;
END;