/* SS_SERVICE_DEPENDENTS Table */
DECLARE iCount NUMBER;
BEGIN
	SELECT COUNT(*) INTO iCount FROM user_tables WHERE table_name = 'SS_SERVICE_DEPENDENTS';
	IF (iCount = 0) THEN
		EXECUTE IMMEDIATE 'CREATE TABLE SS_SERVICE_DEPENDENTS (Dependent_Parent_Service_Id NUMBER, Dependent_Child_Service_Id NUMBER)';
		EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX SS_SERVICE_DEPENDENTS_PK ON SS_SERVICE_DEPENDENTS ("DEPENDENT_PARENT_SERVICE_ID", "DEPENDENT_CHILD_SERVICE_ID")';
		EXECUTE IMMEDIATE 'ALTER TABLE SS_SERVICE_DEPENDENTS ADD CONSTRAINT SS_SERVICE_DEPENDENTS_PK PRIMARY KEY ("DEPENDENT_PARENT_SERVICE_ID", "DEPENDENT_CHILD_SERVICE_ID")';
	END IF;
END;