/* SS_SERVICE_OWNERS Table */
DECLARE iCount NUMBER;
BEGIN
	SELECT COUNT(*) INTO iCount FROM user_tables WHERE table_name = 'SS_SERVICE_OWNERS';
	IF (iCount = 0) THEN
		EXECUTE IMMEDIATE 'CREATE TABLE SS_SERVICE_OWNERS (Owner_User_Id NUMBER, Owner_Service_Id NUMBER)';
		EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX SS_SERVICE_OWNERS_PK ON SS_SERVICE_OWNERS ("OWNER_USER_ID", "OWNER_SERVICE_ID")';
		EXECUTE IMMEDIATE 'ALTER TABLE SS_SERVICE_OWNERS ADD CONSTRAINT SS_SERVICE_OWNERS_PK PRIMARY KEY ("OWNER_USER_ID", "OWNER_SERVICE_ID")';
	END IF;
END;