/* SS_STATUSES Table */
DECLARE iCount NUMBER;
BEGIN
	SELECT COUNT(*) INTO iCount FROM user_tables WHERE table_name = 'SS_STATUSES';
	IF (iCount = 0) THEN
		EXECUTE IMMEDIATE 'CREATE TABLE SS_STATUSES (Status_Id NUMBER, Status_Name VARCHAR2(200 BYTE), Status_Created_By NUMBER, Status_Created_Date DATE, Status_Type VARCHAR2(50 BYTE))';
		EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX SS_STATUSES_PK ON SS_STATUSES ("STATUS_ID")';
		EXECUTE IMMEDIATE 'ALTER TABLE SS_STATUSES ADD CONSTRAINT SS_STATUSES_PK PRIMARY KEY ("STATUS_ID")';
	END IF;
END;