/* SS_SERVICES Table */
DECLARE iCount NUMBER;
BEGIN
	SELECT COUNT(*) INTO iCount FROM user_tables WHERE table_name = 'SS_SERVICES';
	IF (iCount = 0) THEN
		EXECUTE IMMEDIATE 'CREATE TABLE SS_SERVICES (Service_Id NUMBER, Service_Name VARCHAR2(200 BYTE), Service_Description VARCHAR2(2000 BYTE), Service_Parent_Service_Id NUMBER, Service_Current_Status_Id NUMBER, Service_Public VARCHAR2(1 BYTE), Service_Friendly_Url VARCHAR2(200 BYTE), Service_Created_By NUMBER, Service_Sort_Order NUMBER, Service_Department_Id NUMBER, Service_SLA CLOB, Service_Cost CLOB)';
		EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX SS_SERVICES_PK ON SS_SERVICES ("SERVICE_ID")';
		EXECUTE IMMEDIATE 'ALTER TABLE SS_SERVICES ADD CONSTRAINT SS_SERVICES_PK PRIMARY KEY ("SERVICE_ID")';
	END IF;
END;