/* SS_SERVICE_TAGS Table */
DECLARE iCount NUMBER;
BEGIN
	SELECT COUNT(*) INTO iCount FROM user_tables WHERE table_name = 'SS_SERVICE_TAGS';
	IF (iCount = 0) THEN
		EXECUTE IMMEDIATE 'CREATE TABLE SS_SERVICE_TAGS (Tag_Service_Id NUMBER, Tag_Value VARCHAR2(50 BYTE))';
		EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX SS_SERVICE_TAGS_PK ON SS_SERVICE_TAGS ("TAG_SERVICE_ID", "TAG_VALUE")';
		EXECUTE IMMEDIATE 'ALTER TABLE SS_SERVICE_TAGS ADD CONSTRAINT SS_SERVICE_TAGS_PK PRIMARY KEY ("TAG_SERVICE_ID", "TAG_VALUE")';
	END IF;
END;