/* SS_SCHEDULED_MAINTENANCES Table */
DECLARE iCount NUMBER;
BEGIN
	SELECT COUNT(*) INTO iCount FROM user_tables WHERE table_name = 'SS_SCHEDULED_MAINTENANCES';
	IF (iCount = 0) THEN
		EXECUTE IMMEDIATE 'CREATE TABLE SS_SCHEDULED_MAINTENANCES (Maintenance_Id NUMBER, Maintenance_Name VARCHAR2(200 BYTE), Maintenance_Description VARCHAR2(2000 BYTE), Maintenance_Service_Id NUMBER, Maintenance_Offline DATE, Maintenance_Expected_Online DATE, Maintenance_Online DATE, Maintenance_Scheduled_By NUMBER)';
		EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX SS_SCHEDULED_MAINTENANCES_PK ON SS_SCHEDULED_MAINTENANCES ("MAINTENANCE_ID")';
		EXECUTE IMMEDIATE 'ALTER TABLE SS_SCHEDULED_MAINTENANCES ADD CONSTRAINT SS_SCHEDULED_MAINTENANCES_PK PRIMARY KEY ("MAINTENANCE_ID")';
	END IF;
END;