/* SS_USERS Table */
DECLARE iCount NUMBER;
BEGIN
	SELECT COUNT(*) INTO iCount FROM user_tables WHERE table_name = 'SS_USERS';
	IF (iCount = 0) THEN
		EXECUTE IMMEDIATE 'CREATE TABLE SS_USERS (User_Id NUMBER, User_First_Name VARCHAR2(50 BYTE), User_Last_Name VARCHAR2(50 BYTE), User_Hashed_Password VARCHAR2(2000 BYTE), User_Role_Id NUMBER, User_Password_Salt BLOB, User_Active VARCHAR2(1 BYTE))';
		EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX SS_USERS_PK ON SS_USERS ("USER_ID")';
		EXECUTE IMMEDIATE 'ALTER TABLE SS_USERS ADD CONSTRAINT SS_USERS_PK PRIMARY KEY ("USER_ID")';
	END IF;
END;