/* SS_USER_ROLES Table */
DECLARE iCount NUMBER;
BEGIN
	SELECT COUNT(*) INTO iCount FROM user_tables WHERE table_name = 'SS_USER_ROLES';
	IF (iCount = 0) THEN
		EXECUTE IMMEDIATE 'CREATE TABLE SS_USER_ROLES (Role_Id NUMBER, Role_Name VARCHAR2(200 BYTE), Role_Level NUMBER)';
		EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX SS_USER_ROLES_PK ON SS_USER_ROLES ("ROLE_ID")';
		EXECUTE IMMEDIATE 'ALTER TABLE SS_USER_ROLES ADD CONSTRAINT SS_USER_ROLES_PK PRIMARY KEY ("ROLE_ID")';
	END IF;
END;