/* SS_UNPLANNED_STATUSES Table */
DECLARE iCount NUMBER;
BEGIN
	SELECT COUNT(*) INTO iCount FROM user_tables WHERE table_name = 'SS_UNPLANNED_STATUSES';
	IF (iCount = 0) THEN
		EXECUTE IMMEDIATE 'CREATE TABLE SS_UNPLANNED_STATUSES (Status_Id NUMBER, Unplanned_Status_Offline_Since DATE, Unplanned_Status_Exp_Online DATE, Unplanned_Status_Act_Online DATE, Unplanned_Status_Offline_Cause VARCHAR2(2000 BYTE))';
		EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX SS_UNPLANNED_STATUSES_PK ON SS_UNPLANNED_STATUSES ("STATUS_ID")';
		EXECUTE IMMEDIATE 'ALTER TABLE SS_UNPLANNED_STATUSES ADD CONSTRAINT SS_UNPLANNED_STATUSES_PK PRIMARY KEY ("STATUS_ID")';
	END IF;
END;